let paddleHeight = 150;
let ballRadius = 25;
let halfPaddleHeight = paddleHeight / 2;
let speedOfPaddle1 = 0;
let positionOfPaddle1 = 460;
let speedOfPaddle2 = 0;
let positionOfPaddle2 = 460;
let topPositionOfBall = 510;
let leftPositionOfBall = 820;
let topSpeedOfBall = 0;
let leftSpeedOfBall = 0;
let score1;
let score2;